### ISSUE TITLE
JupyterLab 0.33 breaks jupyterlab-drawio

### ISSUE THREAD

**Issue by DeliciousHair** [QuantStack/jupyterlab-drawio#26]
Work computer got re-imaged, rebuilding everything. This lovely package seems to be giving me some grief though (was working perfectly before):

```
$ jupyter labextension install jupyterlab-drawio --debug
...
ValueError: This extension does not yet support the current version of JupyterLab.


Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.17.2 <0.18.0        >=0.16.2 <0.17.0 @jupyterlab/application
>=0.17.2 <0.18.0        >=0.16.2 <0.17.0 @jupyterlab/apputils
>=2.0.2 <3.0.0          >=1.1.2 <2.0.0   @jupyterlab/coreutils
>=0.17.2 <0.18.0        >=0.16.2 <0.17.0 @jupyterlab/filebrowser
>=0.17.2 <0.18.0        >=0.16.2 <0.17.0 @jupyterlab/launcher
```

FWIW, I also have:

```
$ jupyter lab --version
0.33.0

$ jupyter --version
4.4.0
```

Any suggestions greatly appreciated.

 **EDIT** 
I fixed this by downgrading to to jupyterlab 0.32, but I'm going to leave this open for the moment as turns out that 0.33 just made it to PyPi and also seems to break `jupyterlab-drawio`

**Comment by timkpaine** [comment]
relevant docs from [changelog](https://github.com/jupyterlab/jupyterlab/blob/master/CHANGELOG.md)


- Main area widgets like the launcher and console inherit from a common MainAreaWidget class which provides a content area (.content) and a toolbar (.toolbar), consistent focus handling and activation behavior, and a spinner displayed until the given reveal promise is resolved. Document widgets, like the notebook and text editor and other documents opened from the document manager, implement the IDocumentWidget interface (instead of DocumentRegistry.IReadyWidget), which builds on MainAreaWidget and adds a .context attribute for the document context and makes dirty handling consistent. Extension authors may consider inheriting from the MainAreaWidget or DocumentWidget class for consistency. Several effects from these changes are noted below. (#3499, #4453)

**Comment by gauravs2989** [comment]
@DeliciousHair  What is the command to downgrade jupyter lab to 0.32.

**Comment by DeliciousHair** [comment]
`sudo -H pip3 install jupyterlab==0.32`

**Comment by timkpaine** [comment]
an upgrade for 0.33 would be great, 0.33 brings back some good features like inline JS support

**Comment by SylvainCorlay** [comment]
This is now fixed thanks to @Timkpaine

**Comment by belonesox** [comment]
When new version of "jupyterlab-drawio" (with this fix) will be released?

Right now  "jupyter labextension install jupyterlab-drawio" still not worked ("This extension does not yet support the current version of JupyterLab", jupyterlab 0.34), so if  new release of jupyterlab-drawio will be delayed,  I must to patch my deploy scripts....

**Comment by timkpaine** [comment]
This is already out i think, make sure you have jupyterlab 0.34 (`jupyter lab --version`) and are trying to install 0.3.0

**Comment by SylvainCorlay** [comment]
Jupyterlab 0.34 came out yesterday. We will be updating drawio to work with it today or tomorrow.

**Comment by belonesox** [comment]
```
[root@science-test-2 ~]# /usr/bin/jupyter lab --version
0.34.0
[root@science-test-2 ~]# /usr/bin/jupyter labextension install jupyterlab-drawio
> /usr/bin/npm pack jupyterlab-drawio
jupyterlab-drawio-0.3.0.tgz

Errored, use --debug for full output:
ValueError: This extension does not yet support the current version of JupyterLab.


Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.18.2 <0.19.0        >=0.17.2 <0.18.0 @jupyterlab/application
>=0.18.2 <0.19.0        >=0.17.2 <0.18.0 @jupyterlab/apputils
>=0.18.2 <0.19.0        >=0.17.3 <0.18.0 @jupyterlab/filebrowser
>=0.18.2 <0.19.0        >=0.17.2 <0.18.0 @jupyterlab/launcher
```

**Comment by SylvainCorlay** [comment]
That is right, I just said we don't support JupyterLab 0.34 yet. A PR fixing that problem is open already.

That closed issue is about JupyterLab 0.33 support, which is fixed.

**Comment by timkpaine** [comment]
ah whoops, sorry for the misinformation, they're upping major version deps very quickly :-)

**Comment by SylvainCorlay** [comment]
yep, jupyterlab is a fast moving target!

Now all should work with JupyterLab 0.34.

**Comment by cyberwillis** [comment]
And break again :D

```
Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.19.1 <0.20.0        >=0.18.0 <0.19.0 @jupyterlab/application
>=0.19.1 <0.20.0        >=0.18.0 <0.19.0 @jupyterlab/apputils
>=0.19.1 <0.20.0        >=0.18.0 <0.19.0 @jupyterlab/filebrowser
>=0.19.1 <0.20.0        >=0.18.0 <0.19.0 @jupyterlab/launcher

```

**Comment by DinisCruz** [comment]
looks like it is still broken in v.0.35
